name: '🐙😸 GitHub Actions: Check workflows 🕵️'

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '.github/**'

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: 😼 Actionlint
        uses: docker://rhysd/actionlint:1.7.11@sha256:5457037ba91acd225478edac3d4b32e45cf6c10291e0dabbfd2491c63129afe1
        with:
          args: -color

      - name: 🌈 Zizmor
        uses: zizmorcore/zizmor-action@71321a20a9ded102f6e9ce5718a2fcec2c4f70d8 # v0.5.2
        with:
          annotations: true
          advanced-security: false
          color: true
          version: 1.23.1
